def PatternCount(Text, Pattern):
    count = 0
    for i in range(len(Text)-len(Pattern)+1):
        if Text[i:i+len(Pattern)] == Pattern:
            count += 1
    return count

def FrequentWords(Text, k):
    freqPatterns = []
    counts = []
    for i in range(len(Text)-k+1):
        pattern = Text[i:i+k]
        counts.append(PatternCount(Text, pattern))
    maxCount = max(counts)
    for i in range(len(Text)-k+1):
        if counts[i] == maxCount:
            freqPatterns.append(Text[i:i+k])
    return set(freqPatterns) 

FrequentWords('GTCATGCGATCATTTGTCATGCGATCATTTACCCACGTTCGTATGATTTGTAAATTTGTAAAGTCATGCGATCATTTGTCATGCACCCACGGATCATTTTTCGTATGATTTGTAAATTTGTAAAACCCACGACCCACGGATCATTTTTCGTATGATTTGTAAAGTCATGCGATCATTTACCCACGGTCATGCACCCACGGATCATTTTTCGTATGAGATCATTTACCCACGTTTGTAAATTTGTAAATTCGTATGATTCGTATGAACCCACGACCCACGTTCGTATGATTTGTAAAGATCATTTTTTGTAAAGTCATGCGATCATTTTTTGTAAAACCCACGGTCATGCGATCATTTGTCATGCACCCACGACCCACGTTTGTAAATTTGTAAATTCGTATGAGTCATGCGATCATTTTTTGTAAATTCGTATGATTTGTAAAACCCACGACCCACGTTTGTAAAACCCACGTTTGTAAAGATCATTTTTTGTAAATTCGTATGAACCCACGACCCACGGTCATGCTTTGTAAATTCGTATGAACCCACGGATCATTTGTCATGCGTCATGCTTTGTAAAACCCACGTTTGTAAATTTGTAAAGTCATGCTTCGTATGAGTCATGCACCCACGTTTGTAAATTCGTATGAGATCATTTTTTGTAAAGTCATGCTTTGTAAAACCCACGGATCATTTGATCATTTGATCATTTGTCATGCTTTGTAAAACCCACGTTTGTAAATTTGTAAAGTCATGCTTTGTAAAACCCACGTTCGTATGATTTGTAAAACCCACGGTCATGC',11)
